# Generated by Django 4.2.7 on 2025-12-23 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('bitbucket', 'Bitbucket')], default='github', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner', 'provider', 'full_name')},
        ),
        migrations.AlterModelTable(
            name='repository',
            table=None,
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repo_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='webhook_id',
        ),
    ]
