# Generated by Django 4.2.7 on 2025-12-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repos.repository')),
            ],
            options={
                'db_table': 'pull_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('deployment_ready', models.BooleanField(default=False)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='reviews.pullrequest')),
            ],
            options={
                'db_table': 'ai_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.aireview')),
            ],
            options={
                'db_table': 'review_issues',
                'ordering': ['-severity', 'file_path'],
                'indexes': [models.Index(fields=['ai_review', 'severity'], name='review_issu_ai_revi_3eb34c_idx'), models.Index(fields=['severity'], name='review_issu_severit_3747fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', '-created_at'], name='pull_reques_reposit_ffc04e_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['status'], name='pull_reques_status_19c420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'pr_number')},
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['-created_at'], name='ai_reviews_created_3430e1_idx'),
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['risk_score'], name='ai_reviews_risk_sc_791c74_idx'),
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['deployment_ready'], name='ai_reviews_deploym_64ac74_idx'),
        ),
    ]
